apiVersion: apps/v1
kind: Deployment
metadata:
  name: whoami-app
spec:
  template:
    spec:
      nodeSelector:
        cloud.google.com/gke-nodepool: default-pool
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: iap-enabler
spec:
  template:
    spec:
      nodeSelector:
        cloud.google.com/gke-nodepool: default-pool
