apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    app: metacontroller
  name: metacontroller
spec:
  template:
    spec:
      nodeSelector:
        cloud.google.com/gke-nodepool: default-pool
