# Copyright 2020 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

apiVersion: container.cnrm.cloud.google.com/v1beta1
kind: ContainerNodePool
metadata:
  clusterName: "project-id/us-east1-d/name" # {"$kpt-set":"cluster-name"}
  name: gpu-t4-worker-pool01
spec:
  version: cluster-version # {"$kpt-set":"cluster-version"}
  initialNodeCount: 1
  autoscaling:
    minNodeCount: 1
    maxNodeCount: gpu-t4-worker-nodepool-max-size # {"$kpt-set":"gpu-t4-worker-nodepool-max-size"}
  location: us-east1-d # {"$kpt-set":"location"}
  nodeConfig:
    guestAccelerator:
    - count: node-pool-gpu01.gpu-count-per-node # {"$kpt-set":"node-pool-gpu01.gpu-count-per-node"}
      type: nvidia-tesla-t4
    machineType: node-pool-gpu01.instance-type # {"$kpt-set":"node-pool-gpu01.instance-type"}
    metadata:
      disable-legacy-endpoints: "true"
    serviceAccountRef:
      name: name-vm # {"$kpt-set":"name-vm"}
    workloadMetadataConfig:
      nodeMetadata: GKE_METADATA_SERVER
  clusterRef:
    name: name # {"$kpt-set":"name"}
