apiVersion: apps/v1
kind: DaemonSet
metadata:
  labels:
    k8s-app: nvidia-driver-installer
  name: nvidia-driver-installer
  namespace: kube-system
spec:
  selector:
    matchLabels:
      k8s-app: nvidia-driver-installer
  updateStrategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        k8s-app: nvidia-driver-installer
        name: nvidia-driver-installer
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: cloud.google.com/gke-accelerator
                    operator: Exists
      containers:
        - image: gcr.io/google-containers/pause:2.0
          name: pause
      hostNetwork: true
      hostPID: true
      initContainers:
        - env:
            - name: NVIDIA_INSTALL_DIR_HOST
              value: /home/kubernetes/bin/nvidia
            - name: NVIDIA_INSTALL_DIR_CONTAINER
              value: /usr/local/nvidia
            - name: VULKAN_ICD_DIR_HOST
              value: /home/kubernetes/bin/nvidia/vulkan/icd.d
            - name: VULKAN_ICD_DIR_CONTAINER
              value: /etc/vulkan/icd.d
            - name: ROOT_MOUNT_DIR
              value: /root
            - name: COS_TOOLS_DIR_HOST
              value: /var/lib/cos-tools
            - name: COS_TOOLS_DIR_CONTAINER
              value: /build/cos-tools
          image: cos-nvidia-installer:fixed
          imagePullPolicy: Never
          name: nvidia-driver-installer
          resources:
            requests:
              cpu: 0.15
          securityContext:
            privileged: true
          volumeMounts:
            - name: nvidia-install-dir-host
              mountPath: /usr/local/nvidia
            - name: vulkan-icd-mount
              mountPath: /etc/vulkan/icd.d
            - name: dev
              mountPath: /dev
            - name: root-mount
              mountPath: /root
            - name: cos-tools
              mountPath: /build/cos-tools
      tolerations:
        - operator: Exists
      volumes:
        - name: dev
          hostPath:
            path: /dev
        - name: vulkan-icd-mount
          hostPath:
            path: /home/kubernetes/bin/nvidia/vulkan/icd.d
        - name: nvidia-install-dir-host
          hostPath:
            path: /home/kubernetes/bin/nvidia
        - name: root-mount
          hostPath:
            path: /
        - name: cos-tools
          hostPath:
            path: /var/lib/cos-tools
